blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/ryomario/mynotes/discussions
    about: Please visit our discussions page for questions, support, and community discussions.
